### ISSUE TITLE
Question about Steve

### ISSUE THREAD

**Issue by gray311** [rese1f/STEVE#1]
Are the vision tokens directly concatenated with text tokens and then input into Steve? The projection layer is typically needed for vision-text alignments, such as LLaVA. So This confuses me.

**Comment by rese1f** [comment]
Hi, in fact we train a projection layer and directly convert vision token to the text, then we concat it with task instructions to the LLM

**Comment by gray311** [comment]
Thanks for your response. That means your fusion method is similar to Fuyu-8B, right? But doesn't this require feature alignment on plenty of image-text or video-text pairs? Or have you observed that just training on steve-21K can give remarkable results?

**Comment by rese1f** [comment]
Yea, we use the data from our dataset to train that alignment well (since Minecraft vision env is relatively simple), we plan to release our code soon (maybe Dec or Jan), u can find more details there. U can also add my WeChat shown in my profile. Thanks for your interest.

**Comment by gray311** [comment]
Thanks for your response, looking forward to your code being made public, what a very interesting project.
